services:
  - type: web
    name: campussathi-backend
    runtime: node
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FEATHERLESS_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MAIL_PROVIDER
        value: resend
      - key: MAIL_API_KEY
        sync: false
      - key: MAIL_FROM_EMAIL
        sync: false
      - key: MAIL_FROM_NAME
        value: CampusSathi
      - key: MAIL_LOGIN_NOTIFICATIONS
        value: "false"
      - key: CLIENT_URL
        fromService:
          name: campussathi-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: campussathi-frontend
    runtime: static
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: campussathi-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
